# General hooks for all files
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: master
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-json
    - id: check-merge-conflict

# Golang hooks
- repo: https://github.com/dnephin/pre-commit-golang
  rev: master
  hooks:
    - id: go-fmt
      file: server/**/*.go


# Nodejs hooks
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: master
  hooks:
    - id: eslint
      file: client/**/*.js
