# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js Workflow

on:
  pull_request:
    branches: [ master, develop ]
    paths:
      - client/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 11.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Installing dependencies with Node.js ${{ matrix.node-version }}
      working-directory: ./client
      run: npm ci

    - name: Building the project with Node.js ${{ matrix.node-version }}
      working-directory: ./client
      run: npm build --if-present

    - name: Testing the project with Node.js ${{ matrix.node-version }}
      working-directory: ./client
      run: npm test

      env:
        CI: true
